FROM public.ecr.aws/lambda/python:3.13-arm64

# Install build tools
RUN dnf install -y gcc gcc-c++ && dnf clean all

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy lambda function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Copy hdash code
COPY hdash ${LAMBDA_TASK_ROOT}/hdash

# Set the CMD to handler
CMD [ "lambda_function.handler" ]